name: Multi-shell demo

on: [push]

jobs:
  shell-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 1 : Bash
      - name: Bash part
        run: |
          echo "APP_NAME=LaravelApp" >> $GITHUB_ENV
          echo "::group::Affichage Bash"
          echo "Nom de l’application : $APP_NAME"
          echo "::endgroup::"
        shell: bash

      # Étape 2 : Python
      - name: Python part
        run: |
          import os
          print("Nom de l’application :", os.getenv("APP_NAME"))
        shell: python

        
